Modified yaml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -29,6 +29,10 @@ jobs:
         run: cd FrontEnd_New_Design; npm run build --if-present;
         env:
           CI: false
+        working-directory: FrontEnd_New_Design
+
+      - name: Debug npm run build
+        run: npm run build || echo "Build failed with error code $?"
 
   deploy:
     runs-on: windows-latest
